### ISSUE TITLE
Need to add --cool-forms flag to use add-deps

### ISSUE THREAD

**Issue by mchampine** [viebel/klipse-repl#2]
In the README, the --cool-forms flag is not mentioned until after the section describing add-deps.  You actually need to use the --cool-forms flag to be able to use add-deps.

**Comment by viebel** [comment]
Sorry about the delay @mchampine. I missed the notification.
Can you open a Pull Request with an improved README?

**Comment by mchampine** [comment]
Ok, pull request submitted for README.md to mention --cool-forms earlier.  However, now the add-deps fails in a different way. E.g. 

user=> (add-deps '{funcool/cuerdas {:mvn/version "2.0.5"}})
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/mchampine/.m2/repository/org/slf4j/slf4j-nop/1.6.2/slf4j-nop-1.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/mchampine/.m2/repository/ch/qos/logback/logback-classic/1.0.12/logback-classic-1.0.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
Execution error (ArtifactNotFoundException) at org.eclipse.aether.internal.impl.DefaultArtifactResolver/resolve (DefaultArtifactResolver.java:412).
Could not find artifact com.fasterxml.jackson:jackson-base:pom:2.9.7

**Comment by viebel** [comment]
Like, we say sometimes: for me it works

```
➜  ~ clojure -A:klipse-repl --cool-forms
Welcome to Klipse REPL (Read-Eval-Print Loop)
Clojure 1.10.0
 Debugging: (dbg an-expression)
            (dbgdef an-expression)
 Classpath: (classpath)
            (refresh-classpath)
            (add-deps deps-coordinates)
user=> (add-deps '{funcool/cuerdas {:mvn/version "2.0.5"}})
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/viebel/.m2/repository/org/slf4j/slf4j-nop/1.6.2/slf4j-nop-1.6.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/viebel/.m2/repository/ch/qos/logback/logback-classic/1.0.12/logback-classic-1.0.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]
nil
```

My guess is that it relates to a conflict in some library version. Can you try to launch the Klipse REPL from a folder with no Clojure project .

**Comment by mchampine** [comment]
Same behavior with and without a project. I have now fixed the "could not find artifact" error by editing ~/.clojure/deps.edn and uncommenting the :mvn/repos for central and clojars. I still get the binding warnings, but at least add-deps works for me now.  Thanks!

**Comment by viebel** [comment]
Happy to help @mchampine
